### ISSUE TITLE
OT36 - Remove css !important tag

### ISSUE THREAD

**Issue by bappygolder** [bappygolder/oTask#36]
The body background colour uses !important tag for CSS change the code so that it works without the `!important` tag

``` css
    /*update color from #eee to show seperation*/
    html, 
    body{
        background: #e0e0e0 !important; 
    }
```
